package com.naveen.model;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

@Entity
public class Person {
	// Id generated by default by hibernate
	@Id
	@GeneratedValue
	@Column(name="personId_PK")
	private int id;
	private String personName;
	@OneToOne(mappedBy="person", cascade = CascadeType.ALL)
	//@JoinColumn(name = "personDetails_FK")
	private PersonDetails personDetails;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getPersonName() {
		return personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	public PersonDetails getPersonDetails() {
		return personDetails;
	}

	public void setPersonDetails(PersonDetails personDetails) {
		this.personDetails = personDetails;
	}

	@Override
	public String toString() {
		return "Person [id=" + id + ", personName=" + personName + ", personDetails=" + personDetails + "]";
	}

}
