package com.naveen.model;

import java.util.ArrayList;
import java.util.Collection;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;

@Entity
public class Person {
	// Id generated by default by hibernate
	@Id
	@SequenceGenerator(name="gen",allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="gen")
	@Column(name="personId_PK")
	private int id;
	private String personName;
	
	/*@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER) 
	 * // Person_Vehicle default table generated by hibernate 
	private Collection<Vehicle> vehicle = new ArrayList<>();*/
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER) 
	@JoinTable(name="onetomay_table")
	 // @JoinTable just replacing Person_Vehicle default table name to userdefined table name                                                                hibernate 
	private Collection<Vehicle> vehicle = new ArrayList<>();

	public Collection<Vehicle> getVehicle() {
		return vehicle;
	}

	public void setVehicle(Collection<Vehicle> vehicle) {
		this.vehicle = vehicle;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getPersonName() {
		return personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}


	@Override
	public String toString() {
		return "Person [id=" + id + ", personName=" + personName + ", vehicle=" + vehicle + "]";
	}

}
